web:
  image: "leoshi/ttsd-tomcat6"
  ports:
    - "20002:8080"
  volumes:
    - "./ttsd-web/war:/usr/share/tomcat6/webapps"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
pay-wrapper:
  image: "leoshi/ttsd-tomcat6"
  ports:
    - "20003:8080"
  volumes:
    - "./ttsd-pay-wrapper/war:/usr/share/tomcat6/webapps"
  links:
      - "sms-wrapper"
sms-wrapper:
  image: "leoshi/ttsd-tomcat6"
  ports:
    - "20004:8080"
  volumes:
    - "./ttsd-sms-wrapper/war:/usr/share/tomcat6/webapps"
