spring:
  datasource:
    aaro:
      url: jdbc:mysql://192.168.1.249:3306/aa?useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com:
      tuotiansudai:
        diagnosis: debug


